/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mobiquityinc.packer;

import com.mobiquityinc.packer.exception.APIException;
import com.mobiquityinc.packer.exception.ParseException;
import com.mobiquityinc.packer.exception.ReadException;
import com.mobiquityinc.packer.parser.CommonFormatParser;
import com.mobiquityinc.packer.service.PackerReader;
import com.mobiquityinc.packer.service.PackerReaderFactoryProducer;

import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Collectors;

public class Packer {

    public static final String ZERO_FOUND = "-";
    static final String DELIMITER = ",";

    public static String pack(String filePath) throws APIException {

        Path path = Paths.get(filePath);
        if (!Files.exists(path) || !Files.isReadable(path)) {
            throw new APIException("File does not exist or is not readable");
        }
        PackerReader reader = PackerReaderFactoryProducer.getFactory(path.toFile()).getReader();
        try {
            return reader.getResult(new CommonFormatParser(), Collectors.joining(DELIMITER), Collectors.joining(System.getProperty("line.separator")));
        } catch (ParseException | ReadException e) {
            throw new APIException(e.getMessage());
        }
    }

}
