/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mobiquityinc.packer;

import org.junit.Test;
import static org.junit.Assert.*;

public class PackerTest {
    @Test public void testSomeLibraryMethod() {
        Packer classUnderTest = new Packer();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
